[package]
name = "identify"
version = "0.0.2"
description = "OAuth2 authentication and identity management for OpenID Connect and PKCE"
repository = "https://github.com/f0i/identify"
keywords = [
  "authentication",
  "identity",
  "auth",
  "login",
  "openid",
  "oauth2",
  "oidc",
  "pkce"
]
license = "MIT"

[dependencies]
core = "2.5.0"
base = "0.16.0"
ic = "4.0.0"
serde = "3.5.0"
sha2 = "0.2.1"
cbor = "4.1.0"
hex = "1.0.3"
xtended-numbers = "2.3.0"
candid = "2.4.2"

[toolchain]
wasmtime = "37.0.0"
moc = "1.8.2"

[dev-dependencies]
bench = "2.0.1"
test = "2.1.2"
itertools = "0.2.2"
